# Generated by Django 4.0.6 on 2022-08-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(max_length=100)),
                ('end_date', models.DateField()),
                ('time', models.FloatField()),
                ('users', models.ManyToManyField(blank=True, to='Users.user')),
            ],
        ),
    ]
