# Generated by Django 4.0.6 on 2022-08-04 06:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='users',
            field=models.ManyToManyField(related_name='User_Schedule', to=settings.AUTH_USER_MODEL),
        ),
    ]
