# Generated by Django 4.0.6 on 2022-08-09 11:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Schedules', '0004_remove_schedules_users_userschedule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSchedule',
            new_name='User_Schedule',
        ),
    ]
